-- 코드를 입력하세요
SELECT YEAR(S.SALES_DATE) YEAR, MONTH(S.SALES_DATE) MONTH, 
    COUNT(DISTINCT S.USER_ID) PURCHASED_USERS, 
    ROUND( 
        COUNT(DISTINCT S.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE JOINED LIKE '2021%')
        , 1)PUCHASED_RATIO
FROM ONLINE_SALE S
JOIN USER_INFO U ON U.USER_ID = S.USER_ID
WHERE U.JOINED LIKE '2021%'
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;